runtime: python38 # or another supported version

instance_class: F1

env_variables:
  PORT: 8080

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

entrypoint: python app.py		# the command to use for running the app

